### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by robertboccia** [OnFreund/pyrisco#14]
Hey @OnFreund one thing which doesn't pull through on the risco integration is the automation or utility outputs, for example I have gates and garages linked that can be opened via the risco app or via the web interface, but they don't get pulled through as entities in home assistant, so I've added another iot device in home assistant to do the same, duplicated device essentially. Are you able to perhaps pull this through in future iterations?

**Comment by OnFreund** [comment]
Sorry @robertboccia but it's highly unlikely - I don't know the API for this, and don't have it my setup to test.
Since you're already using HA - wouldn't it make more sense to connect the gates through some relay module (e.g. Shelly) instead of through Risco?

**Comment by robertboccia** [comment]
Yeah have done that via a sonoff 4ch pro but was hopefull that this would possibly pull through as it's duplicated basically so have both right now

Robert Boccia
________________________________
