### ISSUE TITLE
CannotConnectError on local connection

### ISSUE THREAD

**Issue by FredericMa** [OnFreund/pyrisco#15]
Hi,

I tried to setup the local Risco integration in HA but it always failed to connect.
Digging a bit deeper I ended up in setting up a small test project to test your library.

It looks like I have a lazy panel because if I add a delay of 1 second after the opening of the connection it works flawlessly.
The line I'm referencing to is here:
https://github.com/OnFreund/pyrisco/blob/ca3f89e1d4851a5db84c97f9b1050df0e0cc6bf2/pyrisco/local/risco_socket.py#L32

This includes my change:
``` python
self._reader, self._writer = await asyncio.open_connection(self._host, self._port)
await asyncio.sleep(1)
```

The panel is from 2013 so it might be a bit slower then newer versions:
![image](https://github.com/OnFreund/pyrisco/assets/7840263/eb67385a-0101-45db-bce2-2d64813f3b4e)

I didn't create a PR since I don't know how you feel about adding a delay just to cover my case.
I don't know if you can add a configurable delay and let it bubble all the way up to the HA integration and make it configurable in the config flow?

**Comment by FredericMa** [comment]
It also looks similar to this issue but there was no solution found so it might be the same cause: https://github.com/home-assistant/core/issues/87008

**Comment by FredericMa** [comment]
Hi @OnFreund, just a friendly ping to get your opinion on the above issue.

**Comment by OnFreund** [comment]
Thanks @FredericMa - I totally missed this (GitHub notifications work in mysterious ways).
Can you create a PR where this is taken from `kwargs` with a default of no sleep? These are passed down through `RiscoLocal` so we can then add it as an option in HA.

**Comment by FredericMa** [comment]
Sure, I'll do that!

**Comment by OnFreund** [comment]
New version with your changes is out at: https://pypi.org/project/pyrisco/0.5.8/

**Comment by FredericMa** [comment]
Cool, thanks. Shall I create a PR for the HA integration to add this delay as an optional parameter or do you prefer to do it yourself?

**Comment by OnFreund** [comment]
You can go for it and I'll review
