### ISSUE TITLE
Agility 3 - mono socket TCP board --- unsupported comands // max. concurrency to high

### ISSUE THREAD

**Issue by jakob1911** [OnFreund/pyrisco#18]
Hello OnFreund,

as answered here [https://github.com/home-assistant/core/issues/103380](https://github.com/home-assistant/core/issues/103380) i want to contribute with the following termes. For me the following was necessary to get my Agility 3 -RW032 - with mono socket TCP board to work --- together with HomeAssistant integration "Risco":

1. "FSVER?" command is not known by my panel. My RW-Panel is using "PNLVER?" which i saw in the communication logs while working with risco configuration software.    ----- You already fired a new version -- should be find with 0.5.9, but not tested right now !

2. When creating the zones i ran into the next error -- not retriving any zone with homeassistant ---->> i figured out that the following two commands are as well not known by my Panel: 
      - the command for the "tech" == "(f'ZLNKTYP{zone_id}?')"
      - the command for the "groups" == "(f'ZAREA&*{zone_id}?')"
 
Please see my snippset on how i modified to got it working (for me only):

![image](https://github.com/OnFreund/pyrisco/assets/112578977/260397e3-6731-4030-92e0-80818b61c5fb)

3. The hardest problem i had so figure out ---- Problem: HomeAssistant is sometimes not retrieving all zones after restart or init. The Problem got worser the more zones i added to the alarm system.....

My solution after lot of trying with the code --- i found the real problem: My old mono socket TCP panel in the Agility 3 gets overloaded with the fast requests when retrieving all the zones in the loop. --_>> My solution is to reduce the parameter "max concurrency" at risco_socket.py from 4 to 2

see the snippset:

![image](https://github.com/OnFreund/pyrisco/assets/112578977/9e37b8d1-f66a-4557-a30e-dd1b76acf7b2)

I hope you can find solutions togehter with my input to reach out the older boards like mine finally. As in the previous reply, i really apprecitate your work and time on the project !

BR 
Jakob

**Comment by OnFreund** [comment]
For future reference, please use text rather than images for code. You can use markup to format it (and preferably show diffs).
I released version 0.5.10 which skips the calls for tech and groups for legacy panels. As for max concurrency, we need to know it before we know the panel type, so we'll have to solve this on the HA side.

**Comment by jakob1911** [comment]
Thanks for the fast implementation. Sorry i will use text with markup for the future.
