### ISSUE TITLE
Risco Local Integration error code N12

### ISSUE THREAD

**Issue by moshiko2312** [OnFreund/pyrisco#19]
HI 
Thanks for  your job  Risco integration   🙏 
Im  on HA 2024.4.3
Working with  Risco Local when im trying  to Disarmed , Away, or Home i getting  error N12
You can tell me how to fix ?
![0556FBE5-CB9F-4CF5-B323-0B45C22C8F51_1_201_a](https://github.com/OnFreund/pyrisco/assets/48163773/ed3e2db3-2cef-48e3-ac8a-e18e87404448)

**Comment by robertboccia** [comment]
I think it's related to zone not being ready, anything in the zone open?

Robert Boccia
________________________________
From: Moshiko ***@***.***>
Sent: Friday, April 19, 2024 12:53:30 PM
To: OnFreund/pyrisco ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [OnFreund/pyrisco] Risco Local Integration error code N12 (Issue #19)


HI
Thanks for your job Risco integration 🙏
Im on HA 2024.4.3
Working with Risco Local when im trying to Disarmed , Away, or Home i getting error N12
You can tell me how to fix ?
0556FBE5-CB9F-4CF5-B323-0B45C22C8F51_1_201_a.jpeg (view on web)<https://github.com/OnFreund/pyrisco/assets/48163773/ed3e2db3-2cef-48e3-ac8a-e18e87404448>

**Comment by moshiko2312** [comment]
ok i will  check  this again 
Thanks

**Comment by moshiko2312** [comment]
Hi thanks for your advice actually one of the sensor do the problem I'm replacing him
