### ISSUE TITLE
2 keyboards  on the same system

### ISSUE THREAD

**Issue by moshiko2312** [OnFreund/pyrisco#23]
Hi if I have 2 keyboards how do I set them up?
I can see one keyboard, and the other keyboard also works but I don't see it in the home assistant integration
What do I have to do to see it too?

**Comment by OnFreund** [comment]
The HA integration exposes partitions, not keyboards.

**Comment by moshiko2312** [comment]
Ok thanks

בתאריך יום ה׳, 19 בדצמ׳ 2024 ב-13:57 מאת On Freund ***@***.***
