### ISSUE TITLE
Following up Out of Memory Error

### ISSUE THREAD

**Issue by IlPicasso** [OnFreund/pyrisco#24]
Hello!

This is a Follow up to the out of memory issues with pyrisco and homeassistant mentioned in this thread, cant continue in it since it is closed.

https://github.com/home-assistant/core/issues/119138

Would be great to have this fixed ! Right now I have risco integration disabled

**Comment by OnFreund** [comment]
[This is](https://github.com/home-assistant/core/issues/119138#issuecomment-2245549348) the last update I can see, but it's going to be on the HA side, not PyRisco side, so I'm closing this.
