### ISSUE TITLE
HA integration: not able to see options for polling timeout

### ISSUE THREAD

**Issue by vergaartel** [OnFreund/pyrisco#28]
Hello everyone. I installed the RISCO integration on my HA installation (latest version 2024.10.4 - supervisor 2024.10.3). However, in the cloud configuration I cannot see the settings related to cloud polling: I only see the switch to disable or re-enable polling and to automate the addition of new sensors. I tried several times to uninstall and reinstall the integration from the repositories but nothing changes. How can I solve it?
Thanks

**Comment by OnFreund** [comment]
1. You're looking in the wrong place. You need to click "Configure", not "System options".
2. As the [documentation](https://www.home-assistant.io/integrations/risco/#how-often-to-poll-risco-cloud-in-seconds/) says: "only shown in advanced mode".
3. This is an HA issue, not PyRisco, so I'm closing it.
