### ISSUE TITLE
Release 

### ISSUE THREAD

**Issue by robertboccia** [OnFreund/pyrisco#8]
Hey @OnFreund when will this be released for home assistant?

**Comment by OnFreund** [comment]
I'm not sure what you mean by "this". Local support was released with 2022.9, and all the latest fixes are included in 2022.9.5

**Comment by robertboccia** [comment]
Ok I haven't seen any change to my risco integration in home assistant, its still connecting to cloud, im on the latest version of home assistant, do I need to uninstall the existing risco integration and reinstall, how do I get it connecting to local instead of cloud?

**Comment by OnFreund** [comment]
When you setup the integration (you'll need to add a new one) you can choose between cloud and local. You can even keep both running if you want.
https://www.home-assistant.io/integrations/risco

**Comment by robertboccia** [comment]
Ah ok wasn't aware of that, thanks so much will go try local tonight, so this means it should not go unavail any longer on local, thank you so much

**Comment by robertboccia** [comment]
I seem to be not able to connect local, keeps saying failed to connect I'm using the panels ip address port 1000 Anda master user pin code?

Robert Boccia
0824971422
________________________________
From: Robert Boccia
Sent: Monday, September 19, 2022 11:52:13 AM
To: OnFreund/pyrisco ***@***.***>; OnFreund/pyrisco ***@***.***>
Cc: Author ***@***.***>
Subject: RE: [OnFreund/pyrisco] Release (Issue #8)


Ah ok wasn’t aware of that, thanks so much will go try local tonight, so this means it should not go unavail any longer on local, thank you so much @***@***.***>

**Comment by OnFreund** [comment]
Please be more specific - what is the error message? What are the logs showing?
Additionally:
1. The code should be the master installer code. By default that's 5678
2. If you have an older board, it might be limited to one connection. You'll have to either disconnect from the cloud (as in program the board to disconnect, not just disable the HA integration), or use a proxy (which I can't help with).

**Comment by robertboccia** [comment]
It worked with your installer code yeeehaaaa

Robert Boccia
0824971422
________________________________

**Comment by robertboccia** [comment]
@OnFreund hey I just wanted to say thank you for the great work on this integration it's so fast really works amazingly well, so nice to be able to use the investment made in risco properly. Thank you @OnFreund

**Comment by robertboccia** [comment]
I have a prosysplus error just says failed to connect when I try local my panels ip address is 10.0.0.48 I assume I out that in host port 1000 I will try with that code

Robert Boccia
0824971422
________________________________
